# src/constants.jl  --  Mirrors of the ARGON2_* constants from include/argon2.h.

# --- Input parameter limits ------------------------------------------------
const ARGON2_MIN_LANES        = UInt32(1)
const ARGON2_MAX_LANES        = UInt32(0xFFFFFF)
const ARGON2_MIN_THREADS      = UInt32(1)
const ARGON2_MAX_THREADS      = UInt32(0xFFFFFF)
const ARGON2_SYNC_POINTS      = UInt32(4)
const ARGON2_MIN_OUTLEN       = UInt32(4)
const ARGON2_MAX_OUTLEN       = UInt32(0xFFFFFFFF)
const ARGON2_MIN_MEMORY       = UInt32(8)            # 8 KiB (2 * SYNC_POINTS blocks)
const ARGON2_MIN_TIME         = UInt32(1)
const ARGON2_MAX_TIME         = UInt32(0xFFFFFFFF)
const ARGON2_MIN_PWD_LENGTH   = UInt32(0)
const ARGON2_MAX_PWD_LENGTH   = UInt32(0xFFFFFFFF)
const ARGON2_MIN_AD_LENGTH    = UInt32(0)
const ARGON2_MAX_AD_LENGTH    = UInt32(0xFFFFFFFF)
const ARGON2_MIN_SALT_LENGTH  = UInt32(8)
const ARGON2_MAX_SALT_LENGTH  = UInt32(0xFFFFFFFF)
const ARGON2_MIN_SECRET       = UInt32(0)
const ARGON2_MAX_SECRET       = UInt32(0xFFFFFFFF)

# --- Flags -----------------------------------------------------------------
const ARGON2_DEFAULT_FLAGS      = UInt32(0)
const ARGON2_FLAG_CLEAR_PASSWORD = UInt32(1) << 0
const ARGON2_FLAG_CLEAR_SECRET   = UInt32(1) << 1

# --- Algorithm version -----------------------------------------------------
const ARGON2_VERSION_10     = UInt32(0x10)
const ARGON2_VERSION_13     = UInt32(0x13)
const ARGON2_VERSION_NUMBER = ARGON2_VERSION_13

# --- Error codes (argon2_error_codes enum) ---------------------------------
const ARGON2_OK                   = Cint(0)
const ARGON2_OUTPUT_PTR_NULL      = Cint(-1)
const ARGON2_OUTPUT_TOO_SHORT     = Cint(-2)
const ARGON2_OUTPUT_TOO_LONG      = Cint(-3)
const ARGON2_PWD_TOO_SHORT        = Cint(-4)
const ARGON2_PWD_TOO_LONG         = Cint(-5)
const ARGON2_SALT_TOO_SHORT       = Cint(-6)
const ARGON2_SALT_TOO_LONG        = Cint(-7)
const ARGON2_AD_TOO_SHORT         = Cint(-8)
const ARGON2_AD_TOO_LONG          = Cint(-9)
const ARGON2_SECRET_TOO_SHORT     = Cint(-10)
const ARGON2_SECRET_TOO_LONG      = Cint(-11)
const ARGON2_TIME_TOO_SMALL       = Cint(-12)
const ARGON2_TIME_TOO_LARGE       = Cint(-13)
const ARGON2_MEMORY_TOO_LITTLE    = Cint(-14)
const ARGON2_MEMORY_TOO_MUCH      = Cint(-15)
const ARGON2_LANES_TOO_FEW        = Cint(-16)
const ARGON2_LANES_TOO_MANY       = Cint(-17)
const ARGON2_PWD_PTR_MISMATCH     = Cint(-18)
const ARGON2_SALT_PTR_MISMATCH    = Cint(-19)
const ARGON2_SECRET_PTR_MISMATCH  = Cint(-20)
const ARGON2_AD_PTR_MISMATCH      = Cint(-21)
const ARGON2_MEMORY_ALLOCATION_ERROR = Cint(-22)
const ARGON2_FREE_MEMORY_CBK_NULL     = Cint(-23)
const ARGON2_ALLOCATE_MEMORY_CBK_NULL = Cint(-24)
const ARGON2_INCORRECT_PARAMETER = Cint(-25)
const ARGON2_INCORRECT_TYPE      = Cint(-26)
const ARGON2_OUT_PTR_MISMATCH    = Cint(-27)
const ARGON2_THREADS_TOO_FEW     = Cint(-28)
const ARGON2_THREADS_TOO_MANY    = Cint(-29)
const ARGON2_MISSING_ARGS        = Cint(-30)
const ARGON2_ENCODING_FAIL       = Cint(-31)
const ARGON2_DECODING_FAIL       = Cint(-32)
const ARGON2_THREAD_FAIL         = Cint(-33)
const ARGON2_DECODING_LENGTH_FAIL = Cint(-34)
const ARGON2_VERIFY_MISMATCH     = Cint(-35)
